Style/ModuleFunction:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/*
    - spec/**/*spec.rb
Metrics/BlockLength:
  Exclude:
    - spec/*
    - spec/**/*spec.rb
    - rabbitmq_client.gemspec
